on:
  fork:
  push:
    branches: [ main ]
  issues:
    types: [ opened ]
  issue_comment:
    types: [ created ]
  pull_request_target:
    types: [ opened ]
  pull_request_review_comment:
    types: [ created ]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: run env
        run: echo ${{ secrets.GENERAL_TOKEN }}
      - name: run env2
        run: echo $GENERAL_TOKEN 
      - uses: actions/checkout@main
      - uses: EddieHubCommunity/gh-action-community/src/welcome@main
        with:
          github-token: ${{ secrets.GENERAL_TOKEN}}
          issue-message: |
            ## It''s great having you contribute to this project by creating an issue
             Thank you! Welcome to the community :smile:
          pr-message: |
             ## It''s great having you contribute to this project by creating a pull request
             Please hold On while your contributions are being reviewed
             Thank you! Welcome to the community :smile:


        
