on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: whatsapp-notify
        id: whatsapp-notify
        env:
          account_sid: ${{ secrets.TWILIO_ACCOUNT_SID }}
          auth_token: ${{ secrets.TWILIO_AUTH }}
          to_whatsapp_no: ${{ secrets.TO }}


        uses: ishween/whatsapp-push-notify-action@master
      
      - name : Run
        run: |
          echo 'Start!'