on: 
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, closed, edited, ready_for_review, review_requested, reopened]
  issues:
    types: [opened, edited, pinned, closed, reopened, assigned, labeled]
  page_build:
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: whatsapp-notify
        id: whatsapp-notify
        env:
          account_sid: ${{ secrets.TWILIO_ACCOUNT_SID }}
          auth_token: ${{ secrets.TWILIO_AUTH }}
          to_whatsapp_no: ${{ secrets.TO }}


        uses: khaled-ibtikar/whatsapp-push-notify-action@master
    